---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
<<<<<<< HEAD
  - npm run lint:hbs
  - npm run lint:js
  - npm test
=======
  - yarn test
>>>>>>> 9230310... v3.15.1...v3.20.0
